In [ ]:
!python --version

## Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. 

To use Numpy, we first need to import the `numpy` package:

In [3]:
import numpy as np

### Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [ ]:
#first array
a = np.array([1, 2, 3])  # Create a 1 dimeniosnal array/ rank 1 array
print(type(a), a[0], a[1], a[2])
a[0] = 5       # Change an element of the array
print("array is:\n",a) 
print("data type of array:",a.dtype)
print("shape of array:", a.shape)

In [ ]:
#second array

b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print("array b is :\n",b)

In [ ]:
print("shape of array is:",b.shape)
print("acessing indivdual elements:",b[0, 0], b[0, 1], b[1, 0])
print("array is :",b)
print("accessing submatrix:\n", b[0: , 0:2])

In [ ]:
#3d array
c  =  np.array([[[1,2,3,8], [4,5,6,7], [3,4,5,10]]])
print(c)
print("-"*40)
print(c.shape)
print(c.ndim)
print("accessing the first element:",c[0,0,0])
print("accessing submatrix:\n", c[0, 0:2, 1:3])

Numpy also provides many functions to create arrays:

In [ ]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

In [ ]:
b = np.ones((2,2))   # Create an array of all ones
print(b)

In [ ]:
c = np.full((2,2), 7) # Create a constant array
print(c)

In [ ]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

In [ ]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

# explore np.random.randint function
# explore np.random.randn function

In [21]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")
arr3 = np.random.rand(10)
arr3

array([0.98808577, 0.2947761 , 0.06005591, 0.32651757, 0.47516381,
       0.41670013, 0.86632614, 0.53739948, 0.8897474 , 0.33956635])

In [23]:

arr4 = np.random.randint(2,5,10)
print("array:", arr4)
print("*"*10)
print("shape is:", arr4.shape)
print("*"*10)
print("dimension:", arr4.ndim)

#arr4
arr5=np.random.randn(2,4,5)
print("arr5:" ,arr5)
#arr6=np.random.random_integers(15)
#arr6

array: [2 2 3 4 2 3 4 4 2 3]
**********
shape is: (10,)
**********
dimension: 1
arr5: [[[-0.59498667  0.85558944  0.6759958   1.74646747 -1.69604113]
  [ 0.69617784  0.3936187  -0.72890612  1.10514724  0.24730125]
  [-1.33279329 -1.30672693 -0.69074032  0.78713296  0.48810961]
  [-0.92870409  0.18140109 -0.40983832 -3.56835148  1.06389967]]

 [[ 0.21993436  0.06087483  0.3078474  -1.02521648 -0.77798879]
  [-0.00535608  0.27996259 -1.46179209 -0.422485    1.4454509 ]
  [ 0.09430418  2.095053    1.21005829  1.5250032   1.1209165 ]
  [-0.12820384 -0.92981666 -0.1854963  -0.29130806  0.84131492]]]


In [26]:
arr7=np.linspace(1,10,100)
#linearly spaced numbers

In [56]:
#2 dimensional arrays

arr8 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D array:", arr8)
print("Dimension : ",arr8.ndim)
print("shape :",arr8.shape)
print("accessing :", arr8[0][0])
print("accessing submatrix: \n", arr8[0:2,0:2])
print("accessing submatrix: \n", arr8[0:2][0:2])
#2 dimensional arrays

print("accessing submatrix1: \n", arr8[1:3][2:3])


2D array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension :  2
shape : (3, 3)
accessing : 1
accessing submatrix: 
 [[1 2]
 [4 5]]
accessing submatrix: 
 [[1 2 3]
 [4 5 6]]
accessing submatrix1: 
 []


In [96]:
arr9=np.arange(10).reshape(5,2)
arr9
#shape will give multidimensioanl, ravel gives single dimensional
arr10=np.ravel(10)
print("ravel:",arr10)
#arr11=np.random.randint((3,3))
arr11=np.ravel([[1,2,3],[4,5,6]])
arr11
arr12=np.zeros(10).reshape(5,2)
arr12
arr13=np.zeros((2,5))
arr13
arr14=np.ones(10)
arr14
arr15=np.eye(10)
print("eye",arr15)
arr16=np.identity(5)
print("identity:",arr16)
arr17=np.arange(10).reshape(5,2)
arr17
#arr18=np.ones_like()
#arr18
#x=np.arrange(10)
#y=np.arrange(10)
#print(x)
#print(y)
#print("add",x+y)
#x1=np.arange(9).reshape(5,4)
#x2=np.arange(9).reshape(5,4)
#print("x1:\n", x1)
#print("x2:\n", x2)
#print(x1+x2)
#print(x1*x2)
w=np.array([[1,2],[3,4]])
u=np.array([[11,12],[13,14]])
print(w)
print(u)
a=np.dot(w,u)
print("dot :\n",a)
#multiplication operator dot

ravel: [10]
eye [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
identity: [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1 2]
 [3 4]]
[[11 12]
 [13 14]]
dot :
 [[37 40]
 [85 92]]


In [110]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [98]:
w=np.array([[1,2],[3,4]])
u=np.array([[11,12],[13,14]])
w.dot(u)

array([[37, 40],
       [85, 92]])

In [106]:
#transpose of a matrix
x1=np.array([[1,2,3],[4,5,6]])
print("x matrix \n", x1)
print("transpose_matrix \n",np.transpose(x1))
print("Transpose using T \n:", x1.T)

x matrix 
 [[1 2 3]
 [4 5 6]]
transpose_matrix 
 [[1 4]
 [2 5]
 [3 6]]
Transpose using T 
: [[1 4]
 [2 5]
 [3 6]]


In [109]:
q1=np.full((3,4),1)
q2=np.full((3,4),2)
q3=np.full((3,4),3)
q4=np.vstack((q1,q2,q3))
q4
#np.hstack  #np.concatenate
q5=np.hstack((q1,q2,q3))
q5
q6=np.concatenate((q1,q2,q3))
q6

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

### Array indexing

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

In [ ]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

Two ways of accessing the data in the middle row of the array.
Mixing integer indexing with slices yields an array of lower rank,
while using only slices yields an array of the same rank as the
original array:

In [111]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a

print(row_r1, row_r1.shape)
print("-------------------")
print(row_r2, row_r2.shape)


[85 92] (2,)
-------------------
[[85 92]] (1, 2)


In [ ]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print('----------------------')
print(col_r2, col_r2.shape)

In [ ]:
#use of arange function

my_array  = np.arange(10) #create array of ten elements
print(my_array)


#create array using start and stop options 

my_array1  =  np.arange(1, 10)
print(my_array1)

#create array using start and stop option and step size

my_array2  =  np.arange(1,10,2)
print(my_array2)


In [ ]:
#reshape function in numpy 

my_array3  =  np.arange(10).reshape(2,5)
print(my_array3)
print('-------------------')
print(my_array3.shape)
print('--------------------')
print(my_array3.ndim)


In [ ]:


a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

### Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x)
print('-----------------')
print(y)
print('-----------------')
# Elementwise sum; both produce the array
print(x + y)
print('-----------------')
print(np.add(x, y))

In [ ]:
# Elementwise difference; both produce the array
print(x - y)
print('---------------')
print(np.subtract(x, y))

In [ ]:
# Elementwise product; both produce the array
print(x * y)
print('-----------------')
print(np.multiply(x, y))

In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)

print('-'*30)

print(np.divide(x, y))

In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

You can also use the `@` operator which is equivalent to numpy's `dot` operator.

In [ ]:
print(v @ w)

In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

In [ ]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [ ]:
print(x)
print("transpose\n", x.T)

In [ ]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

Other useful functions are:
    
- `np.mean` (computes arithmetic mean or average)
- `np.std` (computes the standard deviation)
- `np.var` (computes variance)
- `np.sort` (sorts an array)
- `np.argsort` (returns indices that would sort an array)
- `np.min` (returns the minimum value of an array)
- `np.max` (returns the maximum value of an array)
- `np.argmin` (returns the index of the minimum value)
- `np.argmax` (returns the index of the maximum value)
- `np.array_equal` (checks if two arrays have the same shape and elements)

Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.